---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "tests/.*/reference/.*"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
        # This are JSONC files, which are not strictly valid JSON
        exclude: (?:.devcontainer/devcontainer.json|cspell.json|.vscode/tasks.json)
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: mixed-line-ending
        args:
          - --fix=no
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: local
    hooks:
      - id: bandit-files
        name: Run nox bandit session
        entry: nox -rs bandit --
        language: python
        additional_dependencies: [nox]
        types: [python]
        pass_filenames: true
        require_serial: true
      - id: pylint-files
        name: Run nox pylint session
        entry: nox -rs pylint --
        language: python
        additional_dependencies: [nox]
        types: [python]
        pass_filenames: true
        require_serial: true
      - id: mypy-files
        name: Run nox mypy session
        entry: nox -rs mypy --
        language: python
        additional_dependencies: [nox]
        types: [python]
        pass_filenames: true
        require_serial: true
