---
name: Set up Runner
# Schema: https://json.schemastore.org/github-action.json

inputs:
  os:
    type: string
    description: "The operating system of the runner"
    required: true
  gcc:
    type: string
    description: "The GCC version to use"
    required: true
  python-version:
    type: string
    description: "The python version to use"
    required: true

runs:
  using: 'composite'
  steps:
    # ------------------------------ Ubuntu ------------------------------
    - if: ${{ startsWith(inputs.os,'ubuntu-') && (inputs.gcc != '')}}
      run: sudo apt update
      shell: bash
    - if: ${{ startsWith(inputs.os,'ubuntu-') && (inputs.gcc != '')}}
      run: sudo apt-get install -y make ninja-build ${{ inputs.gcc }} $(echo ${{ inputs.gcc }} | sed -e 's/gcc/g\+\+/') libxml2-utils
      shell: bash

    # ------------------------------ Windows ------------------------------
    - if: ${{ startsWith(inputs.os,'windows-') }}
      uses: msys2/setup-msys2@ddf331adaebd714795f1042345e6ca57bd66cea8
      with:
        install: gcc make
        cache: true

    # ------------------------------ MacOs ------------------------------
    - if: ${{ startsWith(inputs.os,'macos-') }}
      run: HOMEBREW_NO_AUTO_UPDATE=1 brew update
      shell: bash
    - if: ${{ startsWith(inputs.os,'macos-') }}
      run: HOMEBREW_NO_AUTO_UPDATE=1 brew install libxml2
      shell: bash

    # ------------------------------ Python, all OS ------------------------------
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Restore pip cache
      uses: re-actors/cache-python-deps@810325a232f2a28ea124dfba85c7c72fd1774b38
      with:
        cache-key-for-dependency-files: ${{ hashFiles('noxfile.py', 'pyproject.toml', 'doc/requirements.txt') }}
    - run: python3 -m pip install --upgrade pip
      shell: bash
    - run: python3 -m pip install nox requests
      shell: bash
