#!/usr/bin/env python
# -*- coding:utf-8 -*-
#
# This routine generates a format that is similar to the format generated
# by the Python coverage.py module.  This code is similar to the
# data processing performed by lcov's geninfo command.  However, we
# don't worry about parsing the *.gcna files, and backwards compatibility for
# older versions of gcov is not supported.
#
#  _________________________________________________________________________
#
#  Gcovr: A parsing and reporting tool for gcov
#  Copyright (c) 2013 Sandia Corporation.
#  This software is distributed under the BSD License.
#  Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
#  the U.S. Government retains certain rights in this software.
#  For more information, see the README.md file.
# _________________________________________________________________________
#
# $Revision$
# $Date$
#

import sys
import os.path

try:
    import gcovr.driver
except ImportError:
    currdir = os.path.dirname(os.path.abspath(__file__))

    if sys.version_info < (3,0):
        sys.path.append( os.path.abspath( os.path.sep.join([currdir, '..']) ) )
    else:
        sys.path.append( os.path.abspath( os.path.sep.join([currdir, '..', python3]) ) )

    import gcovr.driver

gcovr.driver.main_()


