name: Upload coverage

on:
  workflow_run:
    workflows: ['Run GCOVR Ci']
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@bf251b5aa9c2f7eeb574a96ee720e24f801b7c11
        with:
          name: coverage-.*
          name_is_regexp: true
          run_id: ${{ github.event.workflow_run.id }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage files to Codacy
        if: ${{ (github.repository == 'gcovr/gcovr') }}
        run: |
          # Search the coverage files and upload them
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -l python $(find . -name 'coverage.xml' -print | sed -e 's/^/-r /')
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -l C -r $(find . -name 'coverage.lcov' -print | sed -e 's/^/-r /')
          bash <(curl -Ls https://coverage.codacy.com/get.sh) final

          # Comma separated list of files
          echo "COVERAGE_FILES=$(( find . -name 'coverage.xml' -or -name 'coverage.lcov' -print ) | sed -e '2, $ s/^/,/') >> $GITHUB_ENV
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

      - name: Upload coverage files to Codecov
        if: ${{ (github.repository == 'gcovr/gcovr') }}
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          disable_search: true
          plugins: pycoverage
          files: ${{ env.COVERAGE_FILES }}
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

